# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

p1 = Project.create(preview_image: "http://placehold.it/400x200", main_image: "http://placehold.it/700x500", title: "project 1", short_description: "project 1 short description", long_description: "this description will explain what the site is all about", tech_description: "this description will go over technical details like framework and other shit like that, maybe some interesting tech features")
p2 = Project.create(preview_image: "http://placehold.it/400x200", main_image: "http://placehold.it/700x500", title: "project 2", short_description: "project 2 short description", long_description: "this description will explain what the site is all about", tech_description: "this description will go over technical details like framework and other shit like that, maybe some interesting tech features")
p3 = Project.create(preview_image: "http://placehold.it/400x200", main_image: "http://placehold.it/700x500", title: "project 3", short_description: "project 3 short description", long_description: "this description will explain what the site is all about", tech_description: "this description will go over technical details like framework and other shit like that, maybe some interesting tech features")
p4 = Project.create(preview_image: "http://placehold.it/400x200", main_image: "http://placehold.it/700x500", title: "project 4", short_description: "project 4 short description", long_description: "this description will explain what the site is all about", tech_description: "this description will go over technical details like framework and other shit like that, maybe some interesting tech features")

ProjectSampleImage.create(project: p1, image:"http://placehold.it/350x150", description:"project 1 sample image 1 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
ProjectSampleImage.create(project: p1, image:"http://placehold.it/350x350", description:"project 1 sample image 2 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
ProjectSampleImage.create(project: p2, image:"http://placehold.it/200x150", description:"project 2 sample image 1 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
ProjectSampleImage.create(project: p2, image:"http://placehold.it/350x200", description:"project 2 sample image 2 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
ProjectSampleImage.create(project: p2, image:"http://placehold.it/200x200", description:"project 2 sample image 3 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
ProjectSampleImage.create(project: p3, image:"http://placehold.it/100x100", description:"project 3 sample image 1 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
ProjectSampleImage.create(project: p3, image:"http://placehold.it/350x150", description:"project 3 sample image 2 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
ProjectSampleImage.create(project: p4, image:"http://placehold.it/150x150", description:"project 4 sample image 1 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")